apiVersion: apps/v1
kind: Deployment
metadata:
  name: biharvihaan-redis-deployment
  labels:
    app: biharvihaan-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biharvihaan-redis
  template:
    metadata:
      labels:
        app: biharvihaan-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: biharvihaan-redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: biharvihaan-redis
